# Contadores
## Preparando o ambiente

In [1]:
import pandas as pd

In [3]:
s = pd.Series(list('asdasdasasssassasasdasdsaafdasds'))
s

0     a
1     s
2     d
3     a
4     s
5     d
6     a
7     s
8     a
9     s
10    s
11    s
12    a
13    s
14    s
15    a
16    s
17    a
18    s
19    d
20    a
21    s
22    d
23    s
24    a
25    a
26    f
27    d
28    a
29    s
30    d
31    s
dtype: object

In [4]:
s.unique()

array(['a', 's', 'd', 'f'], dtype=object)

## Realizando contagem
Identificar quantas vezes cada uma das letras foi informada

In [5]:
s.value_counts()

s    14
a    11
d     6
f     1
dtype: int64

## Exercício lançamento moedas

Abaixo, temos o resultado de 50 lançamentos de cada moeda (m1, m2, m3, m4 e m5), onde c representa a ocorrência do evento CARA e C representa a ocorrência do evento COROA.

In [6]:
m1 = 'CCcCCccCCCccCcCccCcCcCCCcCCcccCCcCcCcCcccCCcCcccCc'
m2 = 'CCCCCccCccCcCCCCccCccccCccCccCCcCccCcCcCCcCccCccCc'
m3 = 'CccCCccCcCCCCCCCCCCcccCccCCCCCCccCCCcccCCCcCCcccCC'
m4 = 'cCCccCCccCCccCCccccCcCcCcCcCcCcCCCCccccCCCcCCcCCCC'
m5 = 'CCCcCcCcCcCCCcCCcCcCCccCcCCcccCccCCcCcCcCcCcccccCc'

In [9]:
eventos_moedas = pd.DataFrame({
    'm1': list(m1),
    'm2': list(m2),
    'm3': list(m3),
    'm4': list(m4),
    'm5': list(m5)
})
eventos_moedas

   m1 m2 m3 m4 m5
0   C  C  C  c  C
1   C  C  c  C  C
2   c  C  c  C  C
3   C  C  C  c  c
4   C  C  C  c  C
5   c  c  c  C  c
6   c  c  c  C  C
7   C  C  C  c  c
8   C  c  c  c  C
9   C  c  C  C  c
10  c  C  C  C  C
11  c  c  C  c  C
12  C  C  C  c  C
13  c  C  C  C  c
14  C  C  C  C  C
15  c  C  C  c  C
16  c  c  C  c  c
17  C  c  C  c  C
18  c  C  C  c  c
19  C  c  c  C  C
20  c  c  c  c  C
21  C  c  c  C  c
22  C  c  C  c  c
23  C  C  c  C  C
24  c  c  c  c  c
25  C  c  C  C  C
26  C  C  C  c  C
27  c  c  C  C  c
28  c  c  C  c  c
29  c  C  C  C  c
30  C  C  C  c  C
31  C  c  c  C  c
32  c  C  c  C  c
33  C  c  C  C  C
34  c  c  C  C  C
35  C  C  C  c  c
36  c  c  c  c  C
37  C  C  c  c  c
38  c  c  c  c  C
39  c  C  C  C  c
40  c  C  C  C  C
41  C  c  C  C  c
42  C  C  c  c  C
43  c  c  C  C  c
44  C  c  C  C  c
45  c  C  c  c  c
46  c  c  c  C  c
47  c  c  c  C  c
48  C  C  C  C  C
49  c  c  C  C  c

In [13]:
df = pd.DataFrame(data = ['Cara', 'Coroa'], 
                    index = ['c', 'C'], 
                    columns = ['Faces'])
for item in eventos_moedas:
    df = pd.concat([df, eventos_moedas[item].value_counts()], 
                    axis = 1)
df

   Faces  m1  m2  m3  m4  m5
c   Cara  25  26  19  23  25
C  Coroa  25  24  31  27  25